DO
BEGIN
DECLARE CURSOR C_DBS FOR
	SELECT DATABASE_NAME FROM M_DATABASES;
		
		FOR C_DBS_ROW AS C_DBS DO
		
			DECLARE vDB VARCHAR(10) = C_DBS_ROW.DATABASE_NAME;
			DECLARE vBACKUPID BIGINT = 0;
			DECLARE vTSQL VARCHAR(100) = '';

			SELECT TOP 1 BACKUP_ID INTO vBACKUPID from SYS_DATABASES.M_BACKUP_CATALOG
				WHERE DATABASE_NAME = vDB
				AND STATE_NAME = 'successful'
				AND ENTRY_TYPE_NAME = 'complete data backup'
				ORDER BY BACKUP_ID DESC;
			
			vTSQL = 'BACKUP CATALOG DELETE FOR ' ||vDB|| ' ALL BEFORE BACKUP_ID '||vBACKUPID||' COMPLETE';		

			--SELECT vTSQL FROM DUMMY;
			EXECUTE IMMEDIATE vTSQL;
		END FOR;
END;