module "beacon_server" {
  source                        = "github.com/OpalwaveSolutions/terraform-azure-windows-vm"
  for_each                      = local.beacon_servers
  computer_name                 = each.value.computer_name
  resource_group_name           = azurerm_resource_group.prod.name
  location                      = azurerm_resource_group.prod.location
  subnet_name                   = data.azurerm_subnet.snet-identityservices.name
  subnet_id                     = data.azurerm_subnet.snet-identityservices.id
  zone                          = each.value.zone
  size                          = each.value.size
  source_image_id               = data.azurerm_image.svr2022az.id
  license_type                  = each.value.license_type
  admin_username                = local.admin_username
  admin_password                = data.azurerm_key_vault_secret.local_admin_password.value
  active_directory_domain_name  = local.customer_domain_name
  ad_admin_username             = "joe.hollings.adm"
  ad_admin_password_secret_name = "OWSCS-Joe-ADM"
  rsv_rg_name                   = azurerm_resource_group.prod.name
  recovery_vault_name           = data.azurerm_recovery_services_vault.vault.name
  backup_policy_id              = data.azurerm_backup_policy_vm.WeeklyVMBackup.id
  tags_customer                 = local.customer_name
  tags_environment              = "Prod"
  tags_patching                 = "Prod"
  tags_project                  = "00000"
}